default_job = "clippy"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

[jobs.nextest]
command = [
    "cargo",
    "nextest",
    "run",
    "--hide-progress-bar",
    "--failure-output",
    "final",
]
need_stdout = true
analyzer = "nextest"

[keybindings]
c = "job:clippy"
t = "job:nextest"
