package solipr:file-plugin@0.1.0;

interface kv-store {
    kv-read: func(key: list<u8>) -> option<list<u8>>;
    kv-write: func(key: list<u8>, value: option<list<u8>>);
    kv-keys: func(prefix: list<u8>) -> list<list<u8>>;
}

interface repository {
    record change {
        used-contents: list<string>,
        plugin-data: list<u8>,
    }

    read-change: func(change-hash: string) -> option<change>;
    read-content: func(content-hash: string) -> option<list<u8>>;
    save-content: func(content-data: list<u8>) -> string;
}

world file-plugin {
    use repository.{change};

    import kv-store;
    import repository;

    import render-bytes: func(bytes: list<u8>);
    import render-content: func(content-hash: string);
    export render-file: func();

    export calculate-diff: func(content-hash: string) -> option<change>;
    export apply-change: func(change: change);
    export unapply-change: func(change: change);
}
