package solipr:file-plugin@0.1.0;

interface kv-store {
    kv-read: func(key: list<u8>) -> option<list<u8>>;
    kv-write: func(key: list<u8>, value: option<list<u8>>);
    kv-keys: func(prefix: list<u8>) -> list<list<u8>>;
}

interface repository {
    type change-hash = string;
    type change-data = list<u8>;

    read-change: func(change-hash: change-hash) -> option<change-data>;
}

interface registry {
    type content-hash = string;
    type content-data = list<u8>;

    read-content: func(content-hash: content-hash) -> option<content-data>;
    save-content: func(content-data: content-data) -> content-hash;
}

world file-plugin {
    use repository.{change-hash, change-data};
    use registry.{content-hash, content-data};

    import kv-store;
    import repository;

    import render-bytes: func(bytes: list<u8>);
    import render-content: func(content-hash: content-hash);
    export render-file: func();

    export calculate-diff: func(new-content: list<u8>) -> change-data;
    export apply-change: func(change: change-data);
    export unapply-change: func(change: change-data);
}
