[package]
name = "solipr-plugin-binary"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solipr-plugin = { path = "../plugin" }
borsh = { version = "1.5.3", features = ["derive"] }
